export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST'
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUSTOMER_CREATE_FAIL = 'CUSTOMER_CREATE_FAIL'


export const CUSTOMER_DETAIL_REQUEST = 'CUSTOMER_DETAIL_REQUEST'
export const CUSTOMER_DETAIL_SUCCESS = 'CUSTOMER_DETAIL_SUCCESS'
export const CUSTOMER_DETAIL_FAIL = 'CUSTOMER_DETAIL_FAIL'


export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST'
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS'
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL'


export const CHECK_ORDER_DELIVERY_REQUEST = 'CHECK_ORDER_DELIVERY_REQUEST'
export const CHECK_ORDER_DELIVERY_SUCCESS = 'CHECK_ORDER_DELIVERY_SUCCESS'
export const CHECK_ORDER_DELIVERY_FAIL = 'CHECK_ORDER_DELIVERY_FAIL'


export const FETCH_ALL_CUSTOMERS_REQUEST = 'FETCH_ALL_CUSTOMERS_REQUEST'
export const FETCH_ALL_CUSTOMERS_SUCCESS = 'FETCH_ALL_CUSTOMERS_SUCCESS'
export const FETCH_ALL_CUSTOMERS_FAIL = 'FETCH_ALL_CUSTOMERS_FAIL'