export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'


export const SERVICER_CREATE_REQUEST = 'SERVICER_CREATE_REQUEST'
export const SERVICER_CREATE_SUCCESS = 'SERVICER_CREATE_SUCCESS'
export const SERVICER_CREATE_FAIL = 'SERVICER_CREATE_FAIL'


export const SERVICER_DETAIL_REQUEST = 'SERVICER_DETAIL_REQUEST'
export const SERVICER_DETAIL_SUCCESS = 'SERVICER_DETAIL_SUCCESS'
export const SERVICER_DETAIL_FAIL = 'SERVICER_DETAIL_FAIL'


export const SERVICER_UPDATE_REQUEST = 'SERVICER_UPDATE_REQUEST'
export const SERVICER_UPDATE_SUCCESS = 'SERVICER_UPDATE_SUCCESS'
export const SERVICER_UPDATE_FAIL = 'SERVICER_UPDATE_FAIL'


export const AVAILABLE_UPDATE_REQUEST = 'AVAILABLE_UPDATE_REQUEST'
export const AVAILABLE_UPDATE_SUCCESS = 'AVAILABLE_UPDATE_SUCCESS'
export const AVAILABLE_UPDATE_FAIL = 'AVAILABLE_UPDATE_FAIL'


export const CHECK_ORDER_GIVEN_REQUEST = 'CHECK_ORDER_GIVEN_REQUEST'
export const CHECK_ORDER_GIVEN_SUCCESS = 'CHECK_ORDER_GIVEN_SUCCESS'
export const CHECK_ORDER_GIVEN_FAIL = 'CHECK_ORDER_GIVEN_FAIL'


export const ORDER_STATUS_UPDATE_REQUEST = 'ORDER_STATUS_UPDATE_REQUEST'
export const ORDER_STATUS_UPDATE_SUCCESS = 'ORDER_STATUS_UPDATE_SUCCESS'
export const ORDER_STATUS_UPDATE_FAIL = 'ORDER_STATUS_UPDATE_FAIL'