export const OFFER_ADD_REQUEST = 'OFFER_ADD_REQUEST'
export const OFFER_ADD_SUCCESS = 'OFFER_ADD_SUCCESS'
export const OFFER_ADD_FAIL = 'OFFER_ADD_FAIL'


export const OFFER_UPDATE_REQUEST = 'OFFER_UPDATE_REQUEST'
export const OFFER_UPDATE_SUCCESS = 'OFFER_UPDATE_SUCCESS'
export const OFFER_UPDATE_FAIL = 'OFFER_UPDATE_FAIL'


export const FETCH_ALL_OFFERS_REQUEST = 'FETCH_ALL_OFFERS_REQUEST'
export const FETCH_ALL_OFFERS_SUCCESS = 'FETCH_ALL_OFFERS_SUCCESS'
export const FETCH_ALL_OFFERS_FAIL = 'FETCH_ALL_OFFERS_FAIL'