export const GET_JOINCODE_REQUEST = 'GET_JOINCODE_REQUEST'
export const GET_JOINCODE_SUCCESS = 'GET_JOINCODE_SUCCESS'
export const GET_JOINCODE_FAIL = 'GET_JOINCODE_FAIL'


export const CANCEL_JOINCODE_REQUEST = 'CANCEL_JOINCODE_REQUEST'
export const CANCEL_JOINCODE_SUCCESS = 'CANCEL_JOINCODE_SUCCESS'
export const CANCEL_JOINCODE_FAIL = 'CANCEL_JOINCODE_FAIL'


export const OWNER_SIGNUP_REQUEST = 'OWNER_SIGNUP_REQUEST'
export const OWNER_SIGNUP_SUCCESS = 'OWNER_SIGNUP_SUCCESS'
export const OWNER_SIGNUP_FAIL = 'OWNER_SIGNUP_FAIL'


export const OWNER_DETAIL_REQUEST = 'OWNER_DETAIL_REQUEST'
export const OWNER_DETAIL_SUCCESS = 'OWNER_DETAIL_SUCCESS'
export const OWNER_DETAIL_FAIL = 'OWNER_DETAIL_FAIL'


export const OWNER_UPDATE_REQUEST = 'OWNER_UPDATE_REQUEST'
export const OWNER_UPDATE_SUCCESS = 'OWNER_UPDATE_SUCCESS'
export const OWNER_UPDATE_FAIL = 'OWNER_UPDATE_FAIL'


export const GET_STAT_REQUEST = 'GET_STAT_REQUEST'
export const GET_STAT_SUCCESS = 'GET_STAT_SUCCESS'
export const GET_STAT_FAIL = 'GET_STAT_FAIL'